apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecom-rolebind
  namespace: ecommerce-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecom-role
subjects:
- kind: ServiceAccount
  name: ecom-sa
  namespace: ecommerce-prod
